"""empty message

Revision ID: 091de2f6788f
Revises: 
Create Date: 2024-03-15 20:59:30.954016

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '091de2f6788f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('properties',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=80), nullable=True),
    sa.Column('no_bedrooms', sa.String(length=80), nullable=True),
    sa.Column('no_bathrooms', sa.String(length=80), nullable=True),
    sa.Column('location', sa.String(length=128), nullable=True),
    sa.Column('price', sa.String(length=128), nullable=True),
    sa.Column('description', sa.String(length=256), nullable=True),
    sa.Column('image_name', sa.String(length=256), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('properties')
    # ### end Alembic commands ###
